name: Release (Docker)

on:
  push:
    tags:
      - 'v*' # Trigger on semver tags like v1.0.0, v2.1.3, etc.
    branches-ignore:
      - main

env:
  BUILD_OS_ARCH_LIST: linux-amd64,linux-arm64,darwin-amd64,darwin-arm64
  CI: true

permissions:
  contents: write
  packages: write

jobs:
  test:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/heads/') && github.ref != 'refs/heads/main'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Run tests using Docker Compose
      env:
        CI: ${{ env.CI }}
      run: make test-compose

  build-and-release:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/'))
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 # Required for git describe to work properly

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Extract version from tag
      id: version
      run: |
        # Remove 'v' prefix from tag name
        VERSION=${GITHUB_REF#refs/tags/}
        VERSION=${VERSION#v}
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

    - name: Build binaries and sha256 checksums using Docker Compose
      env:
        BUILD_OS_ARCH_LIST: ${{ env.BUILD_OS_ARCH_LIST }}
        CI: ${{ env.CI }}
      run: make build-compose

    - name: Upload Release Assets
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_REPO: ${{ github.repository }}
        REPO_TAG: ${{ steps.version.outputs.tag }}
        APP_VERSION: ${{ steps.version.outputs.version }}
      run: make gh-release
